### ISSUE TITLE
Adding more flat buttons to the top bar

### ISSUE THREAD

**Issue by Chirag-Mathur** [Chirag-Mathur/CCBlogWebsite-unofficial-#4]

**Comment by Chirag-Mathur** [comment]
adding the following buttons:-
Home
Know Us
Events
Projects
Contact Us

**Comment by Monik09** [comment]
So how you want to add it? like in the middle , all on one side or all space equally

**Comment by Chirag-Mathur** [comment]
just like we have it in design prototype.

**Comment by Chirag-Mathur** [comment]
@Monik09 can I know the status of this issue?

**Comment by Monik09** [comment]
Yeah I am working on more efficient widget tree..

> @Monik09 can I know the status of this issue?

Yeah, I am working on more efficient widget tree.

**Comment by Monik09** [comment]
> @Monik09 can I know the status of this issue?

Yeah, I am working on more efficient widget tree.

**Comment by Chirag-Mathur** [comment]
Ok
